name: mini-build

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
    tags:
      - '*'
      # 手动触发部署
  workflow_dispatch:

jobs:
  mini-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '16'
      # 缓存 node_modules
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      # 缓存
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies   
        run: |
          cd mini
          yarn --prefer-offline --frozen-lockfile
      - name: Uniapp build
        env:
          VUE_APP_BASE_URL: ${{secrets.VUE_APP_BASE_URL}}
        run: |
          cd mini
          yarn build:mp-weixin
      - name: generate key
        id: vars
        env:
          UPLOAD_MP_PRIVATE_KEY: ${{ secrets.UPLOAD_MP_PRIVATE_KEY }}
        run: |
          cd mini
          echo "$UPLOAD_MP_PRIVATE_KEY" > private.key
      - name: upload
        run: |
          cd mini
          npx mp-ci upload --pkp=./private.key ./dist/build/mp-weixin
